config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products do 
    resources :votes, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :votes
  has_many :users, through: :votes

  def score
    votes.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :votes
  has_many :products, through: :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :user, uniqueness: { scope: :product }
  validates :product, uniqueness: { scope: :user }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set this method as a helper method (now available in all controllers/views)

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    flash[:notice] = "Sucessfully Created '#{@product.name}'"
    redirect_to product_path(@product)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to @product
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:alert] = "'#{@product.name}' successfully Deleted"
    redirect_to products_path
  end

private

  def product_params
    params.require(:product).permit(:name, :description, :image_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find User:
    @user = User.find_by(username: params[:session][:username])
    # Authenticate:
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "Invalid. Try Again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = @user.errors_full_messages.join(", ")
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_login

  def create
    @vote = Vote.new(product_id: params[:product_id])
    @product = Product.find(params[:product_id])
    @vote.product = @product 
    @vote.user = current_user

    if @vote.save
      flash[:notice] = "Successfully Voted for '#{@product.name}'"
      redirect_to product_path(params[:product_id])
    else
      flash[:alert] = "Sorry, you've already voted"
      redirect_to product_path(params[:product_id])
    end
  end

  def require_login
    unless current_user
      flash[:alert] = "Sorry, you need to be logged in to do that"
      redirect_to product_path(params[:product_id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.haml
%nav{ class: "navbar navbar-default" }
  %div{ class: "container-fluid" }
    %div{ class: "navbar-header" }
      %p{ class: "navbar-brand" } Turing Bodega
    %div{ class: "navbar-collapse collapse" }
      %ul{ class: "nav navbar-nav" }
        %li= link_to "Home", products_path
        %li= link_to "Add New Product", new_product_path
      %ul{ :class => "nav navbar-nav navbar-right" }
        - if current_user
          %li{ class: "navbar-text", id: "welcome" }= "Welcome, #{current_user.username}!"
          %li= link_to "Logout", logout_path, method: :delete
        - else
          %li= link_to "Login", login_path
          %li= link_to "Sign Up", new_user_path
        

app/views/layouts/application.html.haml
!!!
%html
%head
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
  %title Turing Bodega

%body
  = render 'layouts/navbar'
  %div{ class: "container", id: "flash" }
    - flash.each do |type, msg|
      - if msg.is_a?(String)
        %div{ class: "alert alert-#{type.to_s == 'notice' ? 'success' : 'danger'}" }
          %button{ type: "button", class: "close", "data-dismiss": "alert" }
          = content_tag :div, msg, class: "flash_#{type}"
  %div{ class: "container", id: "content" }
    = yield

app/views/products/edit.html.haml
%h1 Edit Product

= form_for(@product) do |f|
  = f.label :name, "Product Name"
  = f.text_field :name
  = f.label :description, "Description"
  = f.text_area :description
  = f.label :image_path, "Image Path"
  = f.text_area :image_path
  = f.submit

app/views/products/index.html.haml
%h1 All Products

%ul
  - @products.each do |product|
    %li
      Total Votes: 
      = product.score
      = link_to product.name, product_path(product)

app/views/products/new.html.haml
%h1 New Product

= bootstrap_form_for(@product, layout: :horizontal, 
                     label_col: "col-sm-2",
                     control_col: "col-sm-6") do |f|
  = f.text_field :name, label: "Product Name"
  = f.text_area :description
  = f.text_area :image_path, label: "Image Path"
  = f.submit

app/views/products/show.html.haml
%h1= @product.name

%p= image_tag @product.image_path

%h2 Product Description:
%p= @product.description

%h2 
  Total Votes:
  = @product.score

%ul
  - @product.votes.each do |vote|
    - unless vote.user.nil?
      %li= vote.user.username

%p= link_to "Edit", edit_product_path(@product)
%p= link_to "Delete", product_path(@product), method: :delete
%p= link_to "Vote Up", product_votes_path(@product), method: :post

app/views/users/new.html.haml
%h1 Create New Account

= form_for(@user) do |f| 
  = f.label :username, "Username"
  = f.text_field :username 

  = f.label :password, "Password"
  = f.text_field :password 

  = f.submit "Create Account"

app/views/users/show.html.haml
%h1 User Show Page